# tox > output.txt

GLOB sdist-make: /private/tmp/dummy/setup.py
coverage installed: coverage==4.5.1
coverage runtests: PYTHONHASHSEED='1953291279'
coverage runtests: commands[0] | coverage erase
coverage runtests: commands[1] | coverage combine
coverage runtests: commands[2] | coverage xml
coverage runtests: commands[3] | coverage report --show-missing --fail-under=100
Name                Stmts   Miss Branch BrPart  Cover   Missing
---------------------------------------------------------------
dummy/__init__.py       3      3      0      0     0%   1-5
ERROR: InvocationError for command '/private/tmp/dummy/.tox/coverage/bin/coverage report --show-missing --fail-under=100' (exited with code 2)
py3-cover inst-nodeps: /private/tmp/dummy/.tox/dist/dummy-0.0.0.zip
py3-cover installed: attrs==18.1.0,coverage==4.5.1,dummy==0.0.0,more-itertools==4.1.0,pluggy==0.6.0,py==1.5.3,pytest==3.5.1,six==1.11.0
py3-cover runtests: PYTHONHASHSEED='1953291279'
py3-cover runtests: commands[0] | pip install -q dummy[testing]
py3-cover runtests: commands[1] | coverage run --source=dummy /private/tmp/dummy/.tox/py3-cover/bin/pytest
============================= test session starts ==============================
platform darwin -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /private/tmp/dummy, inifile: setup.cfg
collected 1 item

tests/test_module.py .                                                   [100%]

=========================== 1 passed in 0.02 seconds ===========================
Coverage.py warning: No data was collected. (no-data-collected)
py3-cover runtests: commands[2] | coverage xml -o coverage-py3.xml
___________________________________ summary ____________________________________
ERROR:   coverage: commands failed
  py3-cover: commands succeeded
